/**
 * Dados de exemplo usados apenas no "modo demonstração"
 * (quando o Supabase ainda não foi configurado ou não pôde
 * ser alcançado). Nunca são usados quando o app está
 * conectado a um projeto Supabase real.
 */
window.DEMO_ORG = {
  id: "demo-org-1",
  org_name: "Abrigo Amigo Fiel (exemplo)",
  contact_email: "contato@amigofiel.exemplo",
  contact_whatsapp: "5511999990000",
  city: "São Paulo",
  state: "SP",
  instagram: "@amigofiel.exemplo",
  website: "",
  description: "ONG dedicada ao resgate e adoção responsável de cães e gatos na zona leste de SP.",
  logo_url: "",
};

window.DEMO_PETS = [
  {
    id: "demo-1",
    org_id: "demo-org-1",
    name: "Caramelo",
    species: "cachorro",
    size: "Médio",
    age_label: "2 anos",
    description: "Muito brincalhão, adora crianças e já é castrado. Ótimo com outros cães.",
    photo_url: "https://images.unsplash.com/photo-1558788353-f76d92427f16?q=80&w=600&auto=format&fit=crop",
    status: "disponivel",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    city: "São Paulo",
    lives_with_dogs: true,
    lives_with_cats: null,
    lives_with_kids: true,
    apartment_friendly: false,
    personality: ["brincalhao", "sociavel"],
    favorite_toy: "bolinha de tênis",
    created_at: "2026-06-01T12:00:00Z",
    updated_at: "2026-06-01T12:00:00Z",
  },
  {
    id: "demo-2",
    org_id: "demo-org-1",
    name: "Mia",
    species: "gato",
    size: "Pequeno",
    age_label: "8 meses",
    description: "Gatinha dócil, vacinada e vermifugada. Se dá bem sozinha ou com outros gatos.",
    photo_url: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=600&auto=format&fit=crop",
    status: "disponivel",
    vaccinated: true,
    dewormed: true,
    neutered: false,
    city: "São Paulo",
    lives_with_dogs: null,
    lives_with_cats: true,
    lives_with_kids: null,
    apartment_friendly: true,
    personality: ["calmo", "carinhoso"],
    favorite_toy: "",
    created_at: "2026-06-03T12:00:00Z",
    // Sem atualização há mais de 30 dias — deve disparar o aviso de
    // "anúncio desatualizado" no card do admin.
    updated_at: "2026-05-01T12:00:00Z",
  },
  {
    id: "demo-3",
    org_id: "demo-org-1",
    name: "Thor",
    species: "cachorro",
    size: "Grande",
    age_label: "4 anos",
    description: "Cão de guarda tranquilo, já treinado. Está em visita com uma família interessada.",
    photo_url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=600&auto=format&fit=crop",
    status: "em_processo",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    personality: ["protetor", "independente"],
    favorite_toy: "",
    created_at: "2026-05-20T12:00:00Z",
    updated_at: "2026-06-10T15:00:00Z",
  },
  {
    id: "demo-4",
    org_id: "demo-org-1",
    name: "Luna",
    species: "gato",
    size: "Pequeno",
    age_label: "1 ano",
    description: "Curiosa e carinhosa, adora um colo à tarde.",
    photo_url: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=600&auto=format&fit=crop",
    status: "adotado",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    personality: ["carinhoso", "timido"],
    favorite_toy: "colo à tarde",
    created_at: "2026-04-15T12:00:00Z",
    updated_at: "2026-04-20T12:00:00Z",
  },
];

/** Interesses de exemplo, só para ilustrar a tela de admin no modo demonstração. */
window.DEMO_INTERESTS = {
  "demo-1": [
    {
      id: "demo-interest-2",
      pet_id: "demo-1",
      name: "João Pedro",
      email: "joaopedro@exemplo.com",
      phone: "11977776666",
      message: "Moro em casa com quintal, tenho outro cachorro.",
      status: "novo",
      created_at: "2026-07-08T09:00:00Z",
    },
  ],
  "demo-3": [
    {
      id: "demo-interest-1",
      pet_id: "demo-3",
      name: "Fernanda Alves",
      email: "fernanda@exemplo.com",
      phone: "11988887777",
      message: "Tenho quintal grande e já cuidei de cães de porte grande antes.",
      status: "contatado",
      created_at: "2026-06-10T15:30:00Z",
    },
    {
      id: "demo-interest-3",
      pet_id: "demo-3",
      name: "Renata Souza",
      email: "renata@exemplo.com",
      phone: "11966665555",
      message: "",
      status: "arquivado",
      created_at: "2026-06-12T10:15:00Z",
    },
  ],
};
