/**
 * Dados de exemplo usados apenas no "modo demonstração"
 * (quando o Supabase ainda não foi configurado ou não pôde
 * ser alcançado). Nunca são usados quando o app está
 * conectado a um projeto Supabase real.
 */
window.DEMO_ORG = {
  id: "demo-org-1",
  org_name: "Abrigo Amigo Fiel (exemplo)",
  contact_email: "contato@amigofiel.exemplo",
  contact_whatsapp: "5511999990000",
  city: "São Paulo",
  state: "SP",
  instagram: "@amigofiel.exemplo",
  website: "",
  description: "ONG dedicada ao resgate e adoção responsável de cães e gatos na zona leste de SP.",
  logo_url: "",
};

window.DEMO_PETS = [
  {
    id: "demo-1",
    org_id: "demo-org-1",
    name: "Caramelo",
    species: "cachorro",
    size: "Médio",
    age_label: "Jovem",
    photo_url: "https://images.unsplash.com/photo-1558788353-f76d92427f16?q=80&w=600&auto=format&fit=crop",
    status: "disponivel",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    city: "São Paulo",
    lives_with_dogs: true,
    lives_with_cats: null,
    lives_with_kids: true,
    apartment_friendly: false,
    personality: ["brincalhao", "sociavel"],
    favorite_toy: "bolinha de tênis",
    adoption_form_url: "https://forms.example.com/adote-caramelo",
    created_at: "2026-06-01T12:00:00Z",
    updated_at: "2026-06-01T12:00:00Z",
  },
  {
    id: "demo-2",
    org_id: "demo-org-1",
    name: "Mia",
    species: "gato",
    size: "Pequeno",
    age_label: "Filhote",
    photo_url: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=600&auto=format&fit=crop",
    status: "disponivel",
    vaccinated: true,
    dewormed: true,
    neutered: false,
    city: "São Paulo",
    lives_with_dogs: null,
    lives_with_cats: true,
    lives_with_kids: null,
    apartment_friendly: true,
    personality: ["calmo", "carinhoso"],
    favorite_toy: "",
    created_at: "2026-06-03T12:00:00Z",
    // Sem atualização há mais de 30 dias — deve disparar o aviso de
    // "anúncio desatualizado" no card do admin.
    updated_at: "2026-05-01T12:00:00Z",
  },
  {
    id: "demo-3",
    org_id: "demo-org-1",
    name: "Thor",
    species: "cachorro",
    size: "Grande",
    age_label: "Adulto",
    photo_url: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=600&auto=format&fit=crop",
    status: "em_processo",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    personality: ["protetor", "independente"],
    favorite_toy: "",
    created_at: "2026-05-20T12:00:00Z",
    updated_at: "2026-06-10T15:00:00Z",
  },
  {
    id: "demo-4",
    org_id: "demo-org-1",
    name: "Luna",
    species: "gato",
    size: "Pequeno",
    age_label: "Jovem",
    photo_url: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?q=80&w=600&auto=format&fit=crop",
    status: "adotado",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    personality: ["carinhoso", "timido"],
    favorite_toy: "colo à tarde",
    created_at: "2026-04-15T12:00:00Z",
    updated_at: "2026-04-20T12:00:00Z",
  },
  {
    id: "demo-5",
    org_id: "demo-org-1",
    name: "Bidu",
    species: "cachorro",
    size: "Pequeno",
    age_label: "Idoso",
    photo_url: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?q=80&w=600&auto=format&fit=crop",
    status: "disponivel",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    city: "São Paulo",
    lives_with_dogs: true,
    lives_with_cats: true,
    lives_with_kids: true,
    apartment_friendly: true,
    personality: ["calmo", "carinhoso"],
    favorite_toy: "cochilar no sofá",
    created_at: "2026-06-20T09:00:00Z",
    updated_at: "2026-06-20T09:00:00Z",
  },
  {
    id: "demo-6",
    org_id: "demo-org-1",
    name: "Nina",
    species: "gato",
    size: "Médio",
    age_label: "Adulto",
    photo_url: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=600&auto=format&fit=crop",
    status: "disponivel",
    vaccinated: true,
    dewormed: false,
    neutered: true,
    city: "São Paulo",
    lives_with_dogs: false,
    lives_with_cats: null,
    lives_with_kids: true,
    apartment_friendly: true,
    personality: ["independente", "sociavel"],
    favorite_toy: "caixa de papelão",
    created_at: "2026-06-25T14:30:00Z",
    updated_at: "2026-06-25T14:30:00Z",
  },
  {
    id: "demo-7",
    org_id: "demo-org-1",
    name: "Rex",
    species: "cachorro",
    size: "Grande",
    age_label: "Filhote",
    photo_url: "https://images.unsplash.com/photo-1517849845537-4d257902861a?q=80&w=600&auto=format&fit=crop",
    status: "em_processo",
    vaccinated: true,
    dewormed: true,
    neutered: false,
    city: "São Paulo",
    lives_with_dogs: true,
    lives_with_cats: null,
    lives_with_kids: false,
    apartment_friendly: false,
    personality: ["brincalhao", "protetor"],
    favorite_toy: "corda de puxar",
    created_at: "2026-06-28T11:00:00Z",
    updated_at: "2026-07-01T10:00:00Z",
  },
  {
    id: "demo-8",
    org_id: "demo-org-1",
    name: "Amora",
    species: "gato",
    size: "Pequeno",
    age_label: "Jovem",
    photo_url: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?q=80&w=600&auto=format&fit=crop",
    status: "disponivel",
    vaccinated: false,
    dewormed: true,
    neutered: false,
    city: "São Paulo",
    lives_with_dogs: null,
    lives_with_cats: true,
    lives_with_kids: true,
    apartment_friendly: true,
    personality: ["timido", "calmo"],
    favorite_toy: "",
    created_at: "2026-07-02T16:00:00Z",
    updated_at: "2026-07-02T16:00:00Z",
  },
  {
    id: "demo-9",
    org_id: "demo-org-1",
    name: "Zeca",
    species: "cachorro",
    size: "Médio",
    age_label: "Adulto",
    photo_url: "https://images.unsplash.com/photo-1568572933382-74d440642117?q=80&w=600&auto=format&fit=crop",
    status: "adotado",
    vaccinated: true,
    dewormed: true,
    neutered: true,
    city: "São Paulo",
    personality: ["sociavel", "brincalhao"],
    favorite_toy: "bolinha de papel",
    created_at: "2026-05-05T08:00:00Z",
    updated_at: "2026-05-15T08:00:00Z",
  },
];

/** Interesses de exemplo, só para ilustrar a tela de admin no modo demonstração. */
window.DEMO_INTERESTS = {
  "demo-1": [
    {
      id: "demo-interest-2",
      pet_id: "demo-1",
      name: "João Pedro",
      email: "joaopedro@exemplo.com",
      phone: "11977776666",
      message: "Moro em casa com quintal, tenho outro cachorro.",
      status: "novo",
      created_at: "2026-07-08T09:00:00Z",
    },
  ],
  "demo-3": [
    {
      id: "demo-interest-1",
      pet_id: "demo-3",
      name: "Fernanda Alves",
      email: "fernanda@exemplo.com",
      phone: "11988887777",
      message: "Tenho quintal grande e já cuidei de cães de porte grande antes.",
      status: "em_triagem",
      created_at: "2026-06-10T15:30:00Z",
    },
    {
      id: "demo-interest-3",
      pet_id: "demo-3",
      name: "Renata Souza",
      email: "renata@exemplo.com",
      phone: "11966665555",
      message: "",
      status: "arquivado",
      created_at: "2026-06-12T10:15:00Z",
    },
  ],
  "demo-5": [
    {
      id: "demo-interest-4",
      pet_id: "demo-5",
      name: "Carlos Mendes",
      email: "carlos.mendes@exemplo.com",
      phone: "11955554444",
      message: "Meus pais estão aposentados e querem um cão mais tranquilo.",
      status: "novo",
      created_at: "2026-07-05T13:20:00Z",
    },
  ],
  "demo-6": [
    {
      id: "demo-interest-6",
      pet_id: "demo-6",
      name: "Bianca Torres",
      email: "bianca.torres@exemplo.com",
      phone: "11933332222",
      message: "Já tenho outra gata e apartamento telado.",
      status: "aprovado",
      created_at: "2026-06-29T10:00:00Z",
    },
  ],
  "demo-7": [
    {
      id: "demo-interest-5",
      pet_id: "demo-7",
      name: "Patrícia Lima",
      email: "patricia.lima@exemplo.com",
      phone: "11944443333",
      message: "",
      status: "em_contato",
      created_at: "2026-07-02T09:45:00Z",
    },
  ],
  "demo-8": [
    {
      id: "demo-interest-7",
      pet_id: "demo-8",
      name: "Diego Ramos",
      email: "diego.ramos@exemplo.com",
      phone: "11922221111",
      message: "Moro sozinho e trabalho de casa.",
      status: "reprovado",
      created_at: "2026-07-03T12:00:00Z",
    },
  ],
  "demo-9": [
    {
      id: "demo-interest-8",
      pet_id: "demo-9",
      name: "Larissa Nogueira",
      email: "larissa.nogueira@exemplo.com",
      phone: "11911110000",
      message: "Já buscamos o Zeca no fim de semana passado!",
      status: "adocao_concluida",
      created_at: "2026-05-14T09:00:00Z",
    },
  ],
};
